version: '3'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: socialnetwork_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Poonam6201@
      MYSQL_ROOT_PASSWORD: Poonam6201@
    ports:
      - "3306:3306"
